# Generated by Django 3.0.3 on 2020-05-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todos',
            name='backgrond',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='todos',
            name='color',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
